version: '3.6'
services:
  pg_p1_plus_tests:
    image: postgres
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=p1_plus
    container_name: 'pg_p1_plus_tests'
    ports:
      - '54312:5432'
    tmpfs: /var/lib/postgresql/data